### ISSUE TITLE
invalid client id or password

### ISSUE THREAD

**Issue by ghost** [hanula/Pekao24#1]
Hi, I am trying to use it although it's not logging in properly - same thing as i would try to log in with wrong password. I checked all the requests and data sent and it looks same as in my browser. Is it working for you with your pekao24 account? Or maybe something changed on the website and script is outdated?

**Comment by hanula** [comment]
I am using the script every day without any issue. Some other people I know, have automated the script and it's running ever since.

Please check if you're using correct password for your account. It should be _full_ password. Other than that, maybe you have different kind of bank account that uses a different layout? Hard to tell. You could debug it with some `print()`'s and if you find anything, please report back. Watch out for invalid-password limit+lock.

**Comment by ghost** [comment]
Locking after few invalid tries did happen to me but only mobile site was locked and it was enough to log into non-mobile site to unlock it again.  I'll take another look at this. Thank you for your answer.

**Comment by ghost** [comment]
tried it again and still not working. I am getting `invalid id or password` error every time when POSTing password. Checked entered credentials 20 times. Login form should be same even if I have different type of account as you suggested. I'll do some debugging on upcoming weekend.

Python 2.7.9, Lubuntu 15.04, bs4 4.4.0, mechanize 0.2.5.

```
/home/eyveer/.local/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser fo
r this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different 
parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))
Traceback (most recent call last):
  File "./scripts/pekao24", line 26, in <module>
    accounts = client.get_accounts()
  File "/home/eyveer/git/deutsche-bank-client/pekao/pekao24/client.py", line 140, in get_accounts
    self.read_accounts()
  File "/home/eyveer/git/deutsche-bank-client/pekao/pekao24/client.py", line 120, in read_accounts
    self.open_link('lista rachunk')
  File "/home/eyveer/git/deutsche-bank-client/pekao/pekao24/client.py", line 104, in open_link
    response = self._get_opener().follow_link(text_regex=re.compile(text_regex, re.IGNORECASE))
  File "/home/eyveer/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 569, in follow_link
    return self.open(self.click_link(link, **kwds))
  File "/home/eyveer/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 553, in click_link
    link = self.find_link(**kwds)
  File "/home/eyveer/.local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 620, in find_link
    raise LinkNotFoundError()
mechanize._mechanize.LinkNotFoundError
```
